export const GET_ALL_POSTS = 'GET_ALL_POSTS';

export const GET_POSTS = 'GET_POSTS';
export const POSTS_LOADING = 'POSTS_LOADING';
export const ADD_POST = 'ADD_TASK';
export const POSTS_FETCHING_FAIL = 'POSTS_FETCHING_FAIL';
export const DELETE_POST = 'DELETE_TASK';

export const SINGLE_POST_LOADING = 'SINGLE_POST_LOADING';
export const SINGLE_POST_LOADED = 'SINGLE_POST_LOADED';
export const SINGLE_POST_FETCHING_FAIL = 'SINGLE_POST_FETCHING_FAIL';

export const COMMENT_ERROR = 'COMMENT_ERROR';

export const COMMENT_REPLIES_LOADING = 'COMMENT_REPLIES_LOADING';
export const COMMENT_REPLIES_ERROR = 'COMMENT_REPLIES_ERROR';
export const COMMENT_REPLIES_LOADED = 'COMMENT_REPLIES_LOADED';

export const LIKE_TOGGLE = 'LIKE_TOGGLE';
export const LIKE_TOGGLE_LOADING = 'LIKE_TOGGLE_LOADING';
export const LIKE_TOGGLE_ERROR = 'LIKE_TOGGLE_ERROR';

export const GET_USERS = 'GET_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FETCHING_FAIL = 'USERS_FETCHING_FAIL';

export const TOGGLE = 'TOGGLE';
export const HIDE_DROPDOWN = 'HIDE_DROPDOWN';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const TOGGLE_UPLOADER = 'TOGGLE_UPLOADER';
export const TOGGLE_COMMENT_REPLY_BOX = 'TOGGLE_COMMENT_REPLY_BOX';
export const TOGGLE_COMMENT_REPLIES = 'TOGGLE_COMMENT_REPLIES';
export const TOGGLE_THEME = 'TOGGLE_THEME';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const GET_USER_INFO = 'GET_USER_INFO';
export const USER_INFO_LOADING = 'USER_INFO_LOADING';
export const USER_INFO_FETCHING_FAIL = 'USER_INFO_FETCHING_FAIL';

export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_LOADING_FAIL = 'PROFILE_LOADING_FAIL';

export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAIL = 'FOLLOW_FAIL';
export const FOLLOWERS_LOADING = 'FOLLOWERS_LOADING';

export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
