export const GET_POSTS = 'GET_TASKS';
export const POSTS_LOADING = 'POSTS_LOADING';
export const ADD_POST = 'ADD_TASK';
export const POSTS_FETCHING_FAIL = 'POSTS_FETCHING_FAIL';
export const DELETE_POST = 'DELETE_TASK';

export const GET_USERS = 'GET_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FETCHING_FAIL = 'USERS_FETCHING_FAIL';

export const TOGGLE = 'TOGGLE';
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
export const TOGGLE_UPLOADER = 'TOGGLE_UPLOADER';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const GET_USER_INFO = 'GET_USER_INFO';
export const USER_INFO_LOADING = 'USER_INFO_LOADING';
export const USER_INFO_FETCHING_FAIL = 'USER_INFO_FETCHING_FAIL';

export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_LOADED = 'PROFILE_LOADED';
export const PROFILE_LOADING_FAIL = 'PROFILE_LOADING_FAIL';

export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAIL = 'FOLLOW_FAIL';
export const FOLLOWERS_LOADING = 'FOLLOWERS_LOADING';

export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
